from lte import Lte

lte = Lte()
lte.set_input_validity(True)
print("inputs are not verified for correctness here")
lte.insert_line(3, "three")
lte.insert_line(4, "four")
lte.copy_multiple_lines(3,4)
cb = lte.get_clipboard()
print(cb.get_content())
lte.display_contents()
lte.display_specific_lines(1, 2)
lte.insert_line(2, "one")
lte.display_contents()
lte.delete_line(1)
lte.display_contents()
lte.insert_line(8, "eight")
lte.delete_multiple_lines(1, 6)
lte.display_contents()
